const fs = require('fs');
let content = fs.readFileSync('src/components/SecretGame.jsx', 'utf8');

// ConfettiBurst removal
let confetti = "{/* Confetti Burst on Win */}\n        {isWin && transitionStage === 'win_blink' && typeof document !== 'undefined' && createPortal(\n           <div className=\"fixed inset-0 pointer-events-none z-[99999]\">\n              <ConfettiBurst />\n           </div>,\n           document.body\n        )}\n\n        {/* --- DEVELOPER PANEL (Quick Jump Tools) --- */}";
content = content.replace(confetti, "{/* --- DEVELOPER PANEL (Quick Jump Tools) --- */}");

// Revert checkWinCondition
let oldWin = "useEffect(() => {\n      if (gameState === 'playing' && slots.join('') === LEVEL_TARGET.join('')) {\n        setTransitionStage('win_blink'); // Fast blink\n\n        setTimeout(() => {\n          if (currentLevel === 3) {\n             setTransitionStage('chat_climax');\n             setCompletedLevels(3);\n          } else {\n             setTransitionStage('glow');\n             setCompletedLevels(currentLevel);\n             \n             setTimeout(() => {\n                if (currentLevel < LEVELS.length) {\n                   const nextLevel = currentLevel + 1;\n                   setCurrentLevel(nextLevel);\n                   const nextTarget = LEVELS[nextLevel - 1];\n                   setSlots(Array(nextTarget.length).fill(''));\n                   setPlacementHistory([]);\n                   px.set(0);\n                   py.set(0);\n                   setDeck(generateDeck(nextTarget));\n                }\n             }, 1000);\n \n             setTimeout(() => {\n                setTransitionStage('swing');\n             }, 4500); // map drawing delay\n \n             setTimeout(() => {\n                setTransitionStage('fall');\n             }, 5500); // dust pop delay\n \n             setTimeout(() => {\n                setTransitionStage('none');\n             }, 6500);\n          }\n        }, 2500);\n      }\n    }, [slots]);";

let newWin = "useEffect(() => {\n      if (gameState === 'playing' && slots.join('') === LEVEL_TARGET.join('')) {\n        setTimeout(() => {\n           if (currentLevel === 3) {\n              setTransitionStage('chat_climax');\n              setCompletedLevels(3);\n           } else {\n              setTransitionStage('glow');\n              setCompletedLevels(currentLevel);\n              \n              setTimeout(() => {\n                 if (currentLevel < LEVELS.length) {\n                    const nextLevel = currentLevel + 1;\n                    setCurrentLevel(nextLevel);\n                    const nextTarget = LEVELS[nextLevel - 1];\n                    setSlots(Array(nextTarget.length).fill(''));\n                    setPlacementHistory([]);\n                    px.set(0);\n                    py.set(0);\n                    setDeck(generateDeck(nextTarget));\n                 }\n              }, 1000);\n  \n              setTimeout(() => {\n                 setTransitionStage('swing');\n              }, 3500);\n  \n              setTimeout(() => {\n                 setTransitionStage('fall');\n              }, 4300);\n  \n              setTimeout(() => {\n                 setTransitionStage('none');\n              }, 5300);\n           }\n        }, 0);\n      }\n    }, [slots]);";
content = content.replace(oldWin, newWin);

fs.writeFileSync('src/components/SecretGame.jsx', content);
